# Manipulating Dataframes

In the previous tutorial we covered what a dataframe is, and how to create and access it. Now we will look at how to manipulate dataframes and when to use a dataframe as the chosen data structure.

Let's start by importing the pandas library and the football_players.csv we used in the previous tutorial.

In [37]:
import pandas as pd

In [38]:
# Load data - pass 'Name' as our index column
load_df = pd.read_csv('C:/Users/alfred/Downloads/pandas/football_players-a-26.csv', index_col='Name')

# Create dataframe called df
df = pd.DataFrame(load_df)

# Use the head() function to look at the first 5 rows
df.head()

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (14,26) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,Crossing,Curve,Dribbling,Finishing,Free kick accuracy,GK diving,GK handling,GK kicking,GK positioning,GK reflexes,Heading accuracy,Interceptions,Jumping,Long passing,Long shots,Marking,Penalties,Positioning,Reactions,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions
Name,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Cristiano Ronaldo,32,Portugal,94,89,63,89,63,93,95,85,81,91,94,76,7,11,15,14,11,88,29,95,77,92,22,85,95,96,83,94,23,91,92,31,80,85,88,ST LW
L. Messi,30,Argentina,93,92,48,90,95,95,96,77,89,97,95,90,6,11,15,14,8,71,22,68,87,88,13,74,93,95,88,85,26,87,73,28,59,90,85,RW
Neymar,25,Brazil,92,94,56,96,82,95,92,75,81,96,89,84,9,9,15,15,11,62,36,61,75,77,21,81,90,88,81,80,33,90,78,24,53,80,83,LW
L. Su√°rez,30,Uruguay,92,88,78,86,60,91,83,77,86,86,94,84,27,25,31,33,37,77,41,69,64,86,30,85,92,93,83,87,38,77,89,45,80,84,88,ST
M. Neuer,31,Germany,92,58,29,52,35,48,70,15,14,30,13,11,91,90,95,91,89,25,30,78,59,16,10,47,12,85,55,25,11,61,44,10,83,70,11,GK

## Sorting

Usually one of the first things that is done when working with a large dataset is to sort the values using some criteria. This can be done by using the `sort_values()` function. We need to pass the column to sort by. Let's look at some examples:

In [3]:
# Sort by age from youngest to oldest (select first 5 entries)
df.sort_values(by='Age').head()

,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,Crossing,...,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions
Name,,,,,,,,,,,,,,,,,,,,,
J. Romero,16,Argentina,58,75,36,70,86,55,59,46,...,52,54,25,77,58,26,41,51,45,ST
J. Hove,16,Norway,51,57,57,58,56,51,42,40,...,56,50,56,64,47,51,54,56,29,CM
Javi V√°zquez,16,Spain,58,61,53,48,65,47,43,33,...,41,42,59,64,59,63,55,37,29,CB
K. Pierie,16,Netherlands,65,72,64,66,53,65,66,47,...,68,35,62,72,45,67,65,56,32,LB CB
L. Pintor,16,France,54,72,29,70,68,56,43,27,...,30,57,12,68,36,10,34,38,48,ST

When sorting values, the default is always ascending. If we want to sort in decending order, we need to pass ascending=False.

In [4]:
# Sort by age from oldest to youngest (select first 5 entries)
df.sort_values(by='Age', ascending=False).head()

,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,Crossing,...,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions
Name,,,,,,,,,,,,,,,,,,,,,
B. Richardson,47,England,46,25,44,35,44,22,44,11,...,12,13,13,25,32,12,47,17,12,GK
E. El Hadary,44,Egypt,70,28,29,21,41,25,57,20,...,16,18,15,39,34,19,73,16,12,GK
O. P√©rez,44,Mexico,71,60,26,69,69,23,50,19,...,26,24,11,57,41,12,66,40,13,GK
J. Walker,43,England,55,22,41,53,64,38,35,16,...,22,22,13,35,19,11,62,32,11,GK
D. Coyne,43,Wales,55,36,36,48,58,31,57,13,...,28,21,19,33,37,16,76,33,11,GK

## Filtering

A very useful thing to do with a dataframe is to filter the values to only view the data you are interested in. We can do this by passing a condition inside square brackets after the dataframe, eg. the syntax will look like dataframe[condition]. Let's look at a few examples:

In [5]:
# Filter on players older than 30
df[df['Age'] > 30]

,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,Crossing,...,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions
Name,,,,,,,,,,,,,,,,,,,,,
Cristiano Ronaldo,32,Portugal,94,89,63,89,63,93,95,85,...,83,94,23,91,92,31,80,85,88,ST LW
M. Neuer,31,Germany,92,58,29,52,35,48,70,15,...,55,25,11,61,44,10,83,70,11,GK
Sergio Ramos,31,Spain,90,75,84,79,60,84,80,66,...,78,79,91,77,84,89,81,63,66,CB
L. Modriƒá,31,Croatia,89,75,62,93,94,92,84,78,...,92,73,73,71,82,80,58,90,74,CDM CM
G. Chiellini,32,Italy,89,68,92,59,64,57,82,58,...,59,78,90,78,68,92,91,50,45,CB
G. Buffon,39,Italy,89,49,38,55,49,28,70,13,...,37,39,11,43,39,11,69,50,17,GK
D. God√≠n,31,Uruguay,88,62,86,63,58,76,82,55,...,79,67,89,67,67,86,80,52,47,CB
Thiago Silva,32,Brazil,88,70,77,74,68,80,83,60,...,79,74,88,74,74,89,81,74,63,CB
Z. Ibrahimoviƒá,35,Sweden,88,63,84,81,41,88,91,76,...,84,91,27,67,71,41,88,83,90,ST
A. Robben,33,Netherlands,88,87,47,89,91,89,86,80,...,84,87,26,86,68,26,67,83,86,RW RM
David Silva,31,Spain,87,72,51,92,89,90,92,83,...,91,71,29,65,78,44,56,92,79,LM CM CAM
S. Handanoviƒç,32,Slovenia,87,54,25,42,36,24,62,12,...,36,22,13,57,41,10,71,41,12,GK
Iniesta,33,Spain,87,72,58,79,84,94,89,77,...,92,65,56,71,58,57,58,94,74,LM CM
Miranda,32,Brazil,86,67,83,61,57,72,84,48,...,70,70,86,74,65,90,80,58,51,CB
F. Rib√©ry,34,France,86,85,52,88,91,90,86,81,...,86,76,26,79,64,25,60,86,80,LW LM
Pepe,34,Portugal,86,65,94,63,49,62,77,46,...,70,63,87,70,62,86,84,48,23,CB
P. ƒåech,35,Czech Republic,86,40,17,49,34,22,70,19,...,35,21,12,44,32,13,65,53,17,GK
D. Suba≈°iƒá,32,Croatia,85,51,31,42,37,19,65,11,...,24,24,13,54,32,14,80,52,13,GK
C. Marchisio,31,Italy,85,78,78,81,79,85,84,76,...,87,82,80,78,81,78,70,84,76,CDM CM
Filipe Lu√≠s,31,Brazil,85,75,81,74,60,81,88,84,...,78,71,86,82,91,83,74,70,56,LB
V. Kompany,31,Belgium,85,61,87,60,42,68,81,61,...,72,75,84,64,74,85,88,59,46,CB
A. Barzagli,36,Italy,85,64,70,51,64,65,82,40,...,65,54,88,76,46,90,87,62,35,CB
Bruno,33,Spain,84,42,79,53,59,83,86,60,...,87,84,85,41,76,84,77,83,48,CDM CM
E. D≈æeko,31,Bosnia Herzegovina,84,67,51,57,36,80,79,63,...,77,86,16,61,70,28,82,70,77,ST
Falcao,31,Colombia,84,73,75,85,75,82,87,55,...,78,79,19,66,68,42,75,68,84,ST
L. Koscielny,31,France,84,74,88,68,62,67,75,52,...,76,54,84,76,75,87,76,56,35,CB
G. Cahill,31,England,84,62,84,62,51,63,75,28,...,65,63,84,63,69,85,80,56,47,CB
Dani Alves,34,Brazil,84,79,78,85,87,86,82,86,...,83,86,83,84,76,79,55,78,68,RB
Aduriz,36,Spain,84,69,82,53,57,80,87,54,...,71,83,49,70,64,44,83,73,84,ST
M. Mand≈æukiƒá,31,Croatia,83,68,88,67,53,77,80,72,...,75,78,64,76,87,64,87,74,86,LM ST
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
H. Nakabayashi,31,Japan,56,20,26,23,46,19,33,11,...,21,19,35,26,27,20,43,46,5,GK
W. Brown,40,England,56,36,36,31,35,19,29,11,...,16,16,16,22,24,14,62,15,15,GK
D. Pipe,33,Wales,56,61,96,53,72,57,52,60,...,56,36,58,59,67,51,85,53,13,RB RWB
Y. Uekusa,34,Japan,56,63,45,61,56,35,34,35,...,46,40,17,60,44,23,54,48,13,GK
D. Coyne,43,Wales,55,36,36,48,58,31,57,13,...,28,21,19,33,37,16,76,33,11,GK
K. Ishihara,38,Japan,55,36,48,65,75,59,47,54,...,57,53,50,38,36,51,56,55,47,CAM
D. Mulcahy,39,Republic of Ireland,55,27,68,38,52,52,59,52,...,49,56,51,30,34,53,67,55,44,CDM CB
S. Kanazawa,33,Japan,55,47,61,66,73,63,52,53,...,63,67,55,42,33,56,46,48,35,CM CDM
S. Naruoka,33,Japan,55,43,27,82,72,56,57,55,...,58,55,22,43,71,22,62,58,47,RM LM
J. Walker,43,England,55,22,41,53,64,38,35,16,...,22,22,13,35,19,11,62,32,11,GK
N. Ishikawa,36,Japan,55,35,58,70,68,57,57,62,...,59,53,38,45,53,41,60,56,48,RW
K. Tanno,31,Japan,55,26,19,29,49,18,25,14,...,23,23,13,23,22,11,45,45,8,GK
T. Torske,33,Norway,55,61,53,54,68,51,66,49,...,52,44,49,56,65,53,51,52,46,LM LB
K. Singh,31,India,54,47,20,64,62,18,27,14,...,23,15,14,42,33,15,53,15,17,GK
B. Molloy,33,Republic of Ireland,54,32,64,42,49,50,58,41,...,55,42,55,31,33,56,65,50,32,CM CDM
J. McCombe,34,England,54,20,60,23,22,31,54,24,...,39,21,54,21,42,52,75,19,21,CB
J. Robben,34,Germany,54,48,62,56,59,61,55,54,...,65,54,32,61,43,44,66,53,60,RM CDM
J. Bittner,35,England,54,34,34,36,42,25,41,10,...,23,15,13,44,29,15,60,11,14,GK
R. Iuliano,33,Italy,53,30,33,31,45,20,35,17,...,32,28,20,34,24,18,53,33,14,GK
N. Hatta,31,Japan,53,31,22,25,45,12,24,12,...,23,12,13,26,14,12,42,34,10,GK
I. Homma,36,Japan,52,55,50,56,79,41,38,39,...,52,48,52,61,46,57,41,38,25,CDM
R. Kawai,38,Japan,52,39,54,35,55,47,65,39,...,62,37,55,45,30,59,39,40,27,CB CDM
K. Ishii,31,Japan,52,69,29,54,74,49,44,49,...,44,67,24,68,49,24,36,40,53,RW LM RM
Y. Nishibe,36,Japan,52,25,17,25,32,13,67,14,...,29,19,12,24,18,12,49,40,6,GK
A. Al Basisi,39,Saudi Arabia,52,46,22,38,49,20,24,16,...,21,19,20,49,37,13,79,16,11,GK
P. Jennings,37,England,52,38,40,54,50,22,46,18,...,35,24,12,38,37,13,43,21,14,GK
K. Tokushige,33,Japan,51,25,18,38,39,12,41,12,...,31,20,12,20,23,13,62,33,5,GK
H. Tanaka,34,Japan,49,41,92,58,78,42,47,44,...,57,48,49,55,76,41,56,42,35,CDM CM
Y. Uchimura,32,Japan,48,40,31,33,65,57,62,51,...,60,40,42,39,29,42,37,47,38,CAM
B. Richardson,47,England,46,25,44,35,44,22,44,11,...,12,13,13,25,32,12,47,17,12,GK

We can also pass multiple conditions in the square brackets by using the | and & operators. Note that each condition should be closed inside round brackets as well.

In [6]:
# Filter on players older than 30 and overall rating greater than 90
df[(df['Age'] > 30) & (df['Overall'] > 90)]

,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,Crossing,...,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions
Name,,,,,,,,,,,,,,,,,,,,,
Cristiano Ronaldo,32,Portugal,94,89,63,89,63,93,95,85,...,83,94,23,91,92,31,80,85,88,ST LW
M. Neuer,31,Germany,92,58,29,52,35,48,70,15,...,55,25,11,61,44,10,83,70,11,GK

## Create and Drop Columns

Another useful thing is to create new columns from existing ones as well as to drop columns that are not needed.

### Create Columns

We can create new columns from existing ones by simply defining the new name as a string inside square brackets after calling the dataframe followed by the function of the other column(s). Let's look at an example:

In [7]:
# Create column of rating per year of age
df['Rating Per Year of Age'] = df['Overall'] / df['Age']

# Look at first 5 entries
df['Rating Per Year of Age'].head()

Name
Cristiano Ronaldo    2.937500
L. Messi             3.100000
Neymar               3.680000
L. Su√°rez            3.066667
M. Neuer             2.967742
Name: Rating Per Year of Age, dtype: float64

### Drop Columns

Columns can be dropped by using the `drop()` function. The arguments are the column name (string) and the axis which should be equal to 1.

In [8]:
# Drop column just created
df = df.drop('Rating Per Year of Age', axis=1)

df.head()

,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,Crossing,...,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions
Name,,,,,,,,,,,,,,,,,,,,,
Cristiano Ronaldo,32,Portugal,94,89,63,89,63,93,95,85,...,83,94,23,91,92,31,80,85,88,ST LW
L. Messi,30,Argentina,93,92,48,90,95,95,96,77,...,88,85,26,87,73,28,59,90,85,RW
Neymar,25,Brazil,92,94,56,96,82,95,92,75,...,81,80,33,90,78,24,53,80,83,LW
L. Su√°rez,30,Uruguay,92,88,78,86,60,91,83,77,...,83,87,38,77,89,45,80,84,88,ST
M. Neuer,31,Germany,92,58,29,52,35,48,70,15,...,55,25,11,61,44,10,83,70,11,GK

## Group Data

We can also group the data according to some column(s). This will help if we are interested in certain groups within the dataset. We use the `groupby()` function to do this. 

Note that after the `groupby()` function we need to call an aggregation function for the grouped data. Examples are `mean()`, `sum()`, `min()` and `max()`. It will then return a column of the chosen aggregation for each numeric column. We can also then select the columns we want to see. Let's look at an example:

In [9]:
# Look at the average rating by age (first 5 rows)
df.groupby('Age').mean().head()

       Overall
Age
16   57.846154
17   56.089147
18   57.287202
19   59.430309
20   61.559839

It is possible to group by more than one column. We simply need to pass the list of columns.

In [10]:
# Look at the average rating by age and nationality (first 5 rows)
df.groupby(['Age', 'Nationality']).mean().head()

                 Overall
Age Nationality
16  Argentina       56.0
    England         61.5
    France          54.0
    Germany         57.0
    Italy           61.0

## Transforming Data

It is often the case that we want to format a column or columns inside our dataframe. We can transform a column using the `apply()` function, while we use the `applymap()` function to transform all the columns at once. The argument for these functions is a function that must be applied to the specific column or columns. 

We can create a function by using `def` or `lambda expressions`.

### Def Expression

Let's format a column in our dataset. We start by creating the function.

In [11]:
# Using def
def year_to_month(x):
    "Converts no of years to no of months"
    return x * 12

In [12]:
# Change the age column to months and look at first 5 entries
df['Age'].apply(year_to_month).head()

Name
Cristiano Ronaldo    384
L. Messi             360
Neymar               300
L. Su√°rez            360
M. Neuer             372
Name: Age, dtype: int64

### Lambda Expressions

You briefly covered lambda expressions in the Python Fundamentals. But let's have a quick recap:

Lambda operator or lambda function is used for creating small, one-time and anonymous function objects in Python. Basic syntax:

* `lambda` *arguments*: *expression*

Lambda operator can have any number of arguments, but it can have only one expression. It cannot contain any statements and it returns a function object which can be assigned to any variable.

Let's look at an example:

In [13]:
# Using lambda operator
year_to_month_lamb = lambda x: x * 12

# Print function answer
print('def: ', year_to_month(30))
print('lambda: ', year_to_month_lamb(30))

def:  360
lambda:  360

So essentially it does the same as `def`, but it can only have one expression and there is no need to return anything.

Let's use it to format a column in our dataset:

In [14]:
# Change the age column to months and look at first 5 entries
df['Age'].apply(lambda x: x*12).head()

Name
Cristiano Ronaldo    384
L. Messi             360
Neymar               300
L. Su√°rez            360
M. Neuer             372
Name: Age, dtype: int64

### More Examples

For practice, let's create another function to create a column with the player position type, where types can be Forward, Midfielder, Back or GoalKeeper.

In [15]:
# Create function
def position_type(s):
    
    """"This function converts the individual positions (abbreviations) and classfies it
    as either a forward, midfielder, back or goal keeper"""
    
    if (s[-2] == 'T') | (s[-2] == 'W'):
        return 'Forward'
    elif s[-2] == 'M':
        return 'Midfielder'
    elif s[-2] == 'B':
        return 'Back'
    else:
        return 'GoalKeeper'

In [16]:
# Create position type column
df['Preferred Positions Type'] = df['Preferred Positions'].apply(position_type)

# Look at first 5 entries
df['Preferred Positions Type'].head()

Name
Cristiano Ronaldo       Forward
L. Messi                Forward
Neymar                  Forward
L. Su√°rez               Forward
M. Neuer             GoalKeeper
Name: Preferred Positions Type, dtype: object

Let's create another function to transform many columns at once using the `applymap()` function. 

A lot of the columns look like they should be numbers, but are actually stored as strings. We can check this by using the `info()` function:

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17981 entries, Cristiano Ronaldo to L. Sackey
Data columns (total 39 columns):
Age                         17981 non-null int64
Nationality                 17981 non-null object
Overall                     17981 non-null int64
Acceleration                17981 non-null object
Aggression                  17981 non-null object
Agility                     17981 non-null object
Balance                     17981 non-null object
Ball control                17981 non-null object
Composure                   17981 non-null object
Crossing                    17981 non-null object
Curve                       17981 non-null object
Dribbling                   17981 non-null object
Finishing                   17981 non-null object
Free kick accuracy          17981 non-null object
GK diving                   17981 non-null object
GK handling                 17981 non-null object
GK kicking                  17981 non-null object
GK positioning              17981 non-null object
GK reflexes                 17981 non-null object
Heading accuracy            17981 non-null object
Interceptions               17981 non-null object
Jumping                     17981 non-null object
Long passing                17981 non-null object
Long shots                  17981 non-null object
Marking                     17981 non-null object
Penalties                   17981 non-null object
Positioning                 17981 non-null object
Reactions                   17981 non-null object
Short passing               17981 non-null object
Shot power                  17981 non-null object
Sliding tackle              17981 non-null object
Sprint speed                17981 non-null object
Stamina                     17981 non-null object
Standing tackle             17981 non-null object
Strength                    17981 non-null object
Vision                      17981 non-null object
Volleys                     17981 non-null object
Preferred Positions         17981 non-null object
Preferred Positions Type    17981 non-null object
dtypes: int64(2), object(37)
memory usage: 5.5+ MB

As you can see, most of the number columns (attributes) are stored as strings.

We will create a function that transforms all the supposed number columns, to floats. For the strings, we will only select the first two characters to transform so that it returns a two digit number before the comma.

In [18]:
# Select all attribute columns
cols = ['Overall', 'Acceleration', 'Aggression',
       'Agility', 'Balance', 'Ball control', 'Composure', 'Crossing', 'Curve',
       'Dribbling', 'Finishing', 'Free kick accuracy', 'GK diving',
       'GK handling', 'GK kicking', 'GK positioning', 'GK reflexes',
       'Heading accuracy', 'Interceptions', 'Jumping', 'Long passing',
       'Long shots', 'Marking', 'Penalties', 'Positioning', 'Reactions',
       'Short passing', 'Shot power', 'Sliding tackle', 'Sprint speed',
       'Stamina', 'Standing tackle', 'Strength', 'Vision', 'Volleys']

In [19]:
# Create function
def to_float(x):    
    "Transforms attribute columns to type float"
    
    if type(x) is int:
        return float(x)
    else:
        return float(x[0:2])

In [20]:
# Use applymap() function to transform all selected columns
df[cols] = df[cols].applymap(to_float)

Now let's look at the data types of the columns:

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17981 entries, Cristiano Ronaldo to L. Sackey
Data columns (total 39 columns):
Age                         17981 non-null int64
Nationality                 17981 non-null object
Overall                     17981 non-null float64
Acceleration                17981 non-null float64
Aggression                  17981 non-null float64
Agility                     17981 non-null float64
Balance                     17981 non-null float64
Ball control                17981 non-null float64
Composure                   17981 non-null float64
Crossing                    17981 non-null float64
Curve                       17981 non-null float64
Dribbling                   17981 non-null float64
Finishing                   17981 non-null float64
Free kick accuracy          17981 non-null float64
GK diving                   17981 non-null float64
GK handling                 17981 non-null float64
GK kicking                  17981 non-null float64
GK positioning              17981 non-null float64
GK reflexes                 17981 non-null float64
Heading accuracy            17981 non-null float64
Interceptions               17981 non-null float64
Jumping                     17981 non-null float64
Long passing                17981 non-null float64
Long shots                  17981 non-null float64
Marking                     17981 non-null float64
Penalties                   17981 non-null float64
Positioning                 17981 non-null float64
Reactions                   17981 non-null float64
Short passing               17981 non-null float64
Shot power                  17981 non-null float64
Sliding tackle              17981 non-null float64
Sprint speed                17981 non-null float64
Stamina                     17981 non-null float64
Standing tackle             17981 non-null float64
Strength                    17981 non-null float64
Vision                      17981 non-null float64
Volleys                     17981 non-null float64
Preferred Positions         17981 non-null object
Preferred Positions Type    17981 non-null object
dtypes: float64(35), int64(1), object(3)
memory usage: 5.5+ MB

**NB Note:** 

**Use the two functions in this section (More Examples) for your project deliverable to distinguish between defenders (backs) and attackers (forwards), and also to transform your attribute columns to floats (i.e. perform these two transformations on the data before attempting to create the functions required for the project deliverable).**

## Exercises
#### Using the above dataframe, who is the oldest player with an Overall of at least 70?

In [41]:
df[(df['Age'] > 40) & (df['Overall'] > 70)].index[0]

'O. P√©rez'

#### What is the age of the youngest Norweigian player?

In [23]:
df[(df['Nationality'] == 'Norway')]['Age'].min()

16

#### What is the average Overall for Brazillian players that are at least 26 years old?

In [24]:
df[(df['Nationality'] == 'Brazil') & (df['Age'] > 26)]['Overall'].mean()

71.61961722488039

In [25]:
pd.set_option('display.max_rows',10)

In [26]:
df.groupby(['Nationality'])['Overall'].mean()  == 73.0

Nationality
Afghanistan          False
Albania              False
Algeria              False
Angola               False
Antigua & Barbuda    False
                     ...
Venezuela            False
Vietnam              False
Wales                False
Zambia               False
Zimbabwe             False
Name: Overall, Length: 165, dtype: bool

In [27]:
df[(df['Nationality'] == 'Algeria')]['Overall'].index[0]

'R. Mahrez'

In [28]:
df[(df['Preferred Positions Type'] == 'Back')]['Sliding tackle'].index[0]

'Sergio Ramos'

In [29]:
pd.set_option('display.max_rows',1000)

In [30]:
df.groupby(['Nationality', 'Preferred Positions Type'])['Overall'].mean()

Nationality           Preferred Positions Type
Afghanistan           Midfielder                  56.333333
Albania               Back                        68.000000
                      Forward                     63.666667
                      GoalKeeper                  76.000000
                      Midfielder                  65.764706
Algeria               Back                        71.857143
                      Forward                     70.300000
                      GoalKeeper                  66.666667
                      Midfielder                  71.166667
Angola                Back                        70.400000
                      Forward                     68.000000
                      GoalKeeper                  63.000000
                      Midfielder                  68.400000
Antigua & Barbuda     Back                        65.000000
                      Forward                     56.500000
                      Midfielder                  57.500000
Argentina             Back                        68.045775
                      Forward                     67.953125
                      GoalKeeper                  66.229358
                      Midfielder                  67.902632
Armenia               Back                        62.000000
                      Forward                     65.500000
                      Midfielder                  69.000000
Australia             Back                        63.352941
                      Forward                     60.081081
                      GoalKeeper                  62.533333
                      Midfielder                  63.493333
Austria               Back                        65.152941
                      Forward                     63.428571
                      GoalKeeper                  62.714286
                      Midfielder                  64.923077
Azerbaijan            Back                        63.000000
                      Forward                     64.000000
                      Midfielder                  65.500000
Barbados              Forward                     65.000000
Belarus               Back                        72.250000
                      GoalKeeper                  71.000000
                      Midfielder                  69.250000
Belgium               Back                        67.487500
                      Forward                     69.666667
                      GoalKeeper                  67.568182
                      Midfielder                  68.269565
Belize                Midfielder                  64.000000
Benin                 Back                        68.250000
                      Forward                     68.200000
                      GoalKeeper                  67.500000
                      Midfielder                  67.666667
Bermuda               Forward                     66.000000
                      GoalKeeper                  58.000000
                      Midfielder                  63.000000
Bolivia               Back                        65.200000
                      Forward                     65.000000
                      GoalKeeper                  65.250000
                      Midfielder                  65.916667
Bosnia Herzegovina    Back                        69.000000
                      Forward                     70.500000
                      GoalKeeper                  69.000000
                      Midfielder                  69.115385
Brazil                Back                        71.490975
                      Forward                     70.028902
                      GoalKeeper                  71.611940
                      Midfielder                  70.681356
Brunei Darussalam     Midfielder                  55.000000
Bulgaria              Back                        65.363636
                      Forward                     69.166667
                      GoalKeeper                  63.400000
                      Midfielder                  69.454545
Burkina Faso          Back                        66.250000
                      Forward                     66.750000
                      GoalKeeper                  66.000000
                      Midfielder                  72.200000
Burundi               Forward                     64.000000
Cameroon              Back                        67.935484
                      Forward                     67.809524
                      GoalKeeper                  70.571429
                      Midfielder                  66.444444
Canada                Back                        64.428571
                      Forward                     64.909091
                      GoalKeeper                  63.600000
                      Midfielder                  63.560000
Cape Verde            Back                        71.166667
                      Forward                     73.000000
                      GoalKeeper                  63.000000
                      Midfielder                  67.916667
Central African Rep.  Back                        70.000000
                      Forward                     61.000000
                      Midfielder                  68.500000
Chad                  Forward                     74.000000
                      Midfielder                  62.000000
Chile                 Back                        71.007874
                      Forward                     70.423729
                      GoalKeeper                  70.777778
                      Midfielder                  71.013072
China PR              Back                        65.166667
                      Forward                     67.500000
                      GoalKeeper                  71.666667
                      Midfielder                  69.555556
Colombia              Back                        65.527174
                      Forward                     66.823009
                      GoalKeeper                  61.226415
                      Midfielder                  66.231405
Comoros               Back                        69.000000
                      Forward                     71.000000
                      GoalKeeper                  70.000000
                      Midfielder                  67.200000
Congo                 Back                        68.333333
                      Forward                     62.625000
                      GoalKeeper                  65.000000
                      Midfielder                  65.142857
Costa Rica            Back                        71.272727
                      Forward                     64.500000
                      GoalKeeper                  71.666667
                      Midfielder                  69.363636
Croatia               Back                        67.447368
                      Forward                     70.250000
                      GoalKeeper                  67.272727
                      Midfielder                  70.525000
Cuba                  Midfielder                  73.000000
Curacao               Back                        66.666667
                      Forward                     65.000000
                      GoalKeeper                  74.000000
                      Midfielder                  68.200000
Cyprus                Back                        62.833333
                      Forward                     59.500000
                      Midfielder                  63.666667
Czech Republic        Back                        70.173913
                      Forward                     69.538462
                      GoalKeeper                  69.461538
                      Midfielder                  70.916667
DR Congo              Back                        67.000000
                      Forward                     69.785714
                      GoalKeeper                  65.333333
                      Midfielder                  67.541667
Denmark               Back                        63.503817
                      Forward                     63.264151
                      GoalKeeper                  62.166667
                      Midfielder                  63.516667
Dominican Republic    Back                        66.500000
                      Forward                     76.000000
Ecuador               Back                        70.000000
                      Forward                     72.875000
                      GoalKeeper                  70.500000
                      Midfielder                  69.571429
Egypt                 Back                        69.000000
                      Forward                     73.250000
                      GoalKeeper                  70.666667
                      Midfielder                  69.642857
El Salvador           Midfielder                  69.000000
England               Back                        63.669104
                      Forward                     62.513245
                      GoalKeeper                  61.078652
                      Midfielder                  63.393035
Equatorial Guinea     Back                        69.500000
                      Forward                     70.000000
                      GoalKeeper                  67.000000
                      Midfielder                  64.000000
Eritrea               Forward                     71.000000
Estonia               Back                        65.600000
                      Midfielder                  63.333333
Ethiopia              Midfielder                  65.500000
FYR Macedonia         Back                        66.250000
                      Forward                     68.833333
                      GoalKeeper                  67.333333
                      Midfielder                  63.750000
Faroe Islands         Back                        62.000000
                      Forward                     63.500000
                      Midfielder                  58.666667
Fiji                  Forward                     69.000000
Finland               Back                        64.304348
                      Forward                     65.000000
                      GoalKeeper                  61.666667
                      Midfielder                  65.150000
France                Back                        67.483974
                      Forward                     67.161458
                      GoalKeeper                  65.771930
                      Midfielder                  67.661111
Gabon                 Back                        69.333333
                      Forward                     72.666667
                      GoalKeeper                  66.000000
                      Midfielder                  70.800000
Gambia                Back                        68.000000
                      Forward                     64.750000
                      Midfielder                  65.000000
Georgia               Back                        68.500000
                      Forward                     65.166667
                      GoalKeeper                  69.666667
                      Midfielder                  66.285714
Germany               Back                        66.355091
                      Forward                     65.748344
                      GoalKeeper                  65.570513
                      Midfielder                  65.680000
Ghana                 Back                        66.137931
                      Forward                     67.307692
                      GoalKeeper                  59.500000
                      Midfielder                  67.327586
Gibraltar             Back                        64.000000
                      Midfielder                  64.000000
Greece                Back                        69.558824
                      Forward                     69.666667
                      GoalKeeper                  67.466667
                      Midfielder                  68.405405
Grenada               Back                        64.000000
Guam                  Back                        69.000000
Guatemala             GoalKeeper                  72.000000
Guinea                Back                        65.750000
                      Forward                     68.400000
                      Midfielder                  70.181818
Guinea Bissau         Back                        65.000000
                      Forward                     65.500000
                      Midfielder                  66.666667
Guyana                Back                        60.000000
                      Midfielder                  64.000000
Haiti                 Back                        67.500000
                      Forward                     60.500000
                      GoalKeeper                  66.000000
                      Midfielder                  61.600000
Honduras              Back                        70.200000
                      Forward                     71.500000
                      Midfielder                  67.750000
Hong Kong             Midfielder                  54.000000
Hungary               Back                        68.600000
                      Forward                     66.900000
                      GoalKeeper                  69.600000
                      Midfielder                  69.166667
Iceland               Back                        65.875000
                      Forward                     66.692308
                      GoalKeeper                  64.250000
                      Midfielder                  66.250000
India                 Back                        57.100000
                      Forward                     59.100000
                      GoalKeeper                  57.500000
                      Midfielder                  57.500000
Iran                  Back                        68.750000
                      Forward                     70.714286
                      GoalKeeper                  65.666667
                      Midfielder                  65.333333
Iraq                  Back                        66.000000
                      Forward                     68.000000
                      Midfielder                  69.500000
Israel                Back                        69.000000
                      Forward                     73.250000
                      GoalKeeper                  65.000000
                      Midfielder                  71.166667
Italy                 Back                        67.660448
                      Forward                     67.203297
                      GoalKeeper                  64.747748
                      Midfielder                  67.037815
Ivory Coast           Back                        68.407407
                      Forward                     67.200000
                      GoalKeeper                  66.000000
                      Midfielder                  69.375000
Jamaica               Back                        67.142857
                      Forward                     64.000000
                      GoalKeeper                  71.000000
                      Midfielder                  64.909091
Japan                 Back                        62.264286
                      Forward                     63.049180
                      GoalKeeper                  60.541667
                      Midfielder                  62.673469
Kazakhstan            Back                        66.000000
                      Midfielder                  66.000000
Kenya                 Back                        60.500000
                      Forward                     64.000000
                      GoalKeeper                  67.000000
                      Midfielder                  77.000000
Korea DPR             Forward                     63.000000
                      Midfielder                  60.000000
Korea Republic        Back                        64.550459
                      Forward                     64.150943
                      GoalKeeper                  63.804348
                      Midfielder                  64.836066
Kosovo                Back                        66.000000
                      Forward                     68.800000
                      GoalKeeper                  64.000000
                      Midfielder                  65.235294
Kuwait                Back                        61.000000
                      Midfielder                  71.000000
Kyrgyzstan            Forward                     58.000000
Latvia                Back                        63.500000
                      Forward                     69.333333
                      GoalKeeper                  68.500000
Lebanon               Forward                     60.500000
                      GoalKeeper                  61.000000
                      Midfielder                  65.500000
Liberia               Forward                     64.000000
Libya                 Forward                     67.500000
Liechtenstein         Back                        66.000000
                      Forward                     56.000000
                      Midfielder                  73.000000
Lithuania             Back                        66.000000
                      Forward                     68.000000
                      GoalKeeper                  62.000000
                      Midfielder                  63.250000
Luxembourg            Back                        67.666667
                      GoalKeeper                  67.000000
                      Midfielder                  64.500000
Madagascar            Forward                     72.000000
                      Midfielder                  65.000000
Mali                  Back                        67.416667
                      Forward                     68.800000
                      GoalKeeper                  70.000000
                      Midfielder                  66.428571
Malta                 Back                        62.500000
                      Midfielder                  61.000000
Mauritania            Back                        63.000000
                      Midfielder                  70.000000
Mauritius             Midfielder                  67.000000
Mexico                Back                        65.825758
                      Forward                     64.600000
                      GoalKeeper                  63.509804
                      Midfielder                  66.819672
Moldova               Back                        69.000000
                      Midfielder                  70.333333
Montenegro            Back                        70.000000
                      Forward                     71.166667
                      GoalKeeper                  61.000000
                      Midfielder                  67.500000
Montserrat            Back                        67.000000
                      Forward                     66.000000
                      Midfielder                  62.500000
Morocco               Back                        69.111111
                      Forward                     68.315789
                      GoalKeeper                  70.500000
                      Midfielder                  70.512821
Mozambique            Back                        75.500000
                      Forward                     66.000000
Namibia               Back                        63.000000
                      Midfielder                  66.000000
Netherlands           Back                        68.724359
                      Forward                     68.026667
                      GoalKeeper                  65.841270
                      Midfielder                  68.348148

In [31]:
df[(df['Age'] == df['Age'].max())]['Nationality']

Name
B. Richardson    England
Name: Nationality, dtype: object

In [32]:
df.groupby(['Preferred Positions Type'])['Reactions','Acceleration'].mean()

                          Reactions  Acceleration
Preferred Positions Type
Back                      61.522230     64.384405
Forward                   62.030741     71.011682
GoalKeeper                59.470867     40.229749
Midfielder                62.655931     69.126163

In [33]:
pd.set_option('display.max_columns',1000)

In [34]:
df.groupby(['Preferred Positions Type']).mean()

,Age,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,Crossing,Curve,Dribbling,Finishing,Free kick accuracy,GK diving,GK handling,GK kicking,GK positioning,GK reflexes,Heading accuracy,Interceptions,Jumping,Long passing,Long shots,Marking,Penalties,Positioning,Reactions,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys
Preferred Positions Type,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Back,25.436731,66.495383,64.384405,65.494699,60.121067,61.526334,57.074213,58.661594,51.287278,43.687073,51.841997,34.787449,39.387141,10.597982,10.598324,10.602941,10.601744,10.566860,60.916211,63.728112,68.800616,53.082421,39.892613,64.180404,43.962722,43.440834,61.522230,58.344562,51.924077,65.404412,65.448358,68.021888,66.863543,70.360123,45.786423,35.974863
Forward,24.630188,66.209038,71.011682,51.642176,68.462650,65.883800,64.982170,60.876729,50.086689,53.173071,64.525361,65.780203,46.353827,10.499846,10.628343,10.676606,10.499231,10.537658,60.642484,27.517369,66.074085,46.835229,59.583461,23.739010,62.285583,64.881033,62.030741,58.867507,66.457117,24.522902,71.493083,64.523517,26.908392,66.409468,56.045804,58.225330
GoalKeeper,26.016580,64.811937,40.229749,27.578873,41.912364,44.454287,21.961630,37.512080,16.028423,16.665088,16.203221,14.516817,16.126480,62.988157,60.675983,59.424443,60.843676,63.848887,16.108479,18.032212,58.339176,26.719090,15.131691,13.270962,22.028423,13.803411,59.470867,28.401705,24.290857,14.606821,40.526291,32.057793,14.806253,60.914732,37.171009,14.906206
Midfielder,24.867336,66.500813,69.126163,58.194563,70.186143,70.731275,66.696115,61.945191,58.689171,57.126311,65.186586,53.928645,53.280396,10.544837,10.618407,10.672773,10.594918,10.625055,52.087753,49.643817,62.829665,62.454277,57.502290,45.943566,55.285862,58.760674,62.655931,67.055843,63.356774,48.032501,68.427390,68.020830,50.474664,61.504210,62.587236,51.078889

In [35]:
df['Preferred Positions Type'].value_counts()

Midfielder    6769
Back          5848
Forward       3253
GoalKeeper    2111
Name: Preferred Positions Type, dtype: int64

In [36]:
df[(df['Nationality'] == 'Portugal') & (df['Age'] < 25)]['Overall'].index[0]

'Bernardo Silva'

## When to use Dataframes

DataFrames allow you to store and manipulate tabular data in rows of observations and columns of variables. It is therefore a two-dimensional labeled data structure. We should use a pandas dataframe if all of the following statements hold:

* We have 2-dimensional data (rows and columns)
* The data type is the same within a column
* We are interested in the index (rows) and column names

That is the end of this tutorial. You should have a better understanding of how to manipulate pandas dataframes. You have now covered all of the tutorials in the Python Data Structures section of the course. Well done!!!